### ISSUE TITLE
Menu dropdown has weird behavior

### ISSUE THREAD

**Issue by bigint** [Doist/reactist#304] opened 2020-08-24 06:34 UTC
### Current behavior

Menu dropdown has weird behavior while scrolling, and it has huge margin top from he trigger button

### Steps to reproduce the bug

https://www.loom.com/share/0d281be0e51d47a3826755b333c1da3c

### Environment

- `@doist/reactist` version: dev
- Browser: Brave `Chrome/84.0.4147.135`

**Comment by gnapse** [comment] 2020-08-24 16:04
Hmmm, that's weird. I can't reproduce that.

Also, what that screen recording suggests is not a huge margin, but it's like if the menu dropdown moves along when you scroll.

Still, no luck reproduce it here. Would love to figure out why you get that behavior, under what conditions. Did you run `npm run storybook` locally and get this behavior?

**Comment by bigint** [comment] 2020-08-25 12:21
Yes I did run `npm run storybook` locally in the `dev` branch!

**Comment by gnapse** [comment] 2020-08-25 13:02
But do you have more insight on why this happens to you? The more I try this the more I see it does not happen. Can you try in another chromium browsers or maybe an incognito window or something? Or at least confirm for us if it happens for you in general in other browsers or just on Chrome?

**Comment by bigint** [comment] 2020-08-25 13:23
@gnapse This is not happening now in both Brave and Chrome browser!

But this looks weird! I don't know how that happens previously!

**Comment by gnapse** [comment] 2020-08-25 13:38
Ok, glad to hear that. Indeed weird. But I'll close this for now. Thanks!

**Closed by gnapse** 2020-08-25 13:38 UTC
